### ISSUE TITLE
Recreated zx spectrum compatibility 

### ISSUE THREAD

**Issue by Japetusgr** [bog-dan-ro/spectacol#107]
Hi, as the recreated zx spectrum kickstarter project came to a dead-end, many of these bluetooth keyboards are now selling quite cheaply and some third party projects have begun to provide compatibility with them. This being the case, someone provided a patch to make fuse compatible with the keyboard and thus I am wondering if it would be easy to implement this feature to spectacol also since it is based on fuse. 
http://blogs.newphoria.de/2016/04/15/using-recreated-zx-spectrum-with-fuse-1-1-1-emulator/

**Comment by bog-dan-ro** [comment]
AFAIK Fuse 1.2.0 added support for the recreated zx spectrum, did you try it with Spectacol 2.5?

**Comment by bog-dan-ro** [comment]
I'm wrong, the patch is on the patch pending list but was not merged yet.

**Comment by Japetusgr** [comment]
Thanks for upstreaming this issue!

**Comment by bog-dan-ro** [comment]
Well, the "patch" is already upstreamed https://sourceforge.net/p/fuse-emulator/patches/358/ ... we need to wait until FUSE devs will merge it.

**Comment by bog-dan-ro** [comment]
https://github.com/bog-dan-ro/spectacol/commit/b871957b315643574635d444b51f2ae81507c8b6

**Comment by gabormarinov** [comment]
Hi,
I have a recreated zx spectrum, and its really a killer feature, thanks for incorporating. However a few keys don't work, but there's a recent patch for fixing that:
https://sourceforge.net/p/fuse-emulator/patches/358/?limit=25

Could you merge that, hanks.

**Comment by bog-dan-ro** [comment]
@gabormarinov : I've uploaded v3.0.5 to beta channel (it will take several hors until will be visible), please become a beta tester (use the beta tester button in google play or follow this https://play.google.com/apps/testing/eu.licentia.games.spectacol link) and test it for me. I don't have such keyboard so, it was a blind fix.

**Comment by gabormarinov** [comment]
@bog-dan-ro  It's working perfectly now, thank you for the quick response!

**Comment by bog-dan-ro** [comment]
@gabormarinov thanks! moved 3.0.5 to production.
