### ISSUE TITLE
Load Poke files that match automatically & hide them from list view 

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#108]
If the '.pok' file is named exactly the same as the game file then it should automatically load it and let the user choose which pokes to activate in the 'Poke Memory' section. Fuse does this.

Also an option to prevent .pok files from displaying in the file selector.

**Comment by ghost** [comment]
I don't know if you're still working on this emulator or the very time consuming metadata thing.

When loading .pok files manually it sometimes turns on the first cheat. Is it detecting button presses too soon ?

When loading some cheat files why are some of the cheats automatically turned on ? What turns these cheats on ? Is it an incompatibility with the game version ?

**Comment by sbaldovi** [comment]
> When loading some cheat files why are some of the cheats automatically turned on ? What turns these cheats on ? Is it an incompatibility with the game version ?

Most likely, the memory address already have the value to poke. Could you provide an example to examine?

**Comment by ghost** [comment]
I can't remember which ones they were now. It may have been Spectacol confusing me because it often turns on the first cheat when loading the .pok file. I may also have been using a incompatible version or already bugfixed version and a cheat was for the bugfix.

**Comment by ghost** [comment]
So this will automatically load the .pok file if the filename is exactly the same (and we can choose which cheats to turn on/off in the 'poke memory' menu) ? If so, is it also possible to add a optional toggle to hide .pok files from the file list as they almost double the file count ?

**Comment by sbaldovi** [comment]
The Fuse code also allows to store/hide the pok files in a folder:

> It  is  possible to load POKEs from an external file using the File, Open...  menu option or the drag-and-drop functionality in the GTK+ and Win32 UIs.  After loading a snapshot or tape, Fuse will try to automatically locate a POK file with the same file name. This means that if we open `GAME.TAP', then Fuse will try to open 'GAME.POK' and 'POKES/GAME.POK'.

Some zips from WOS have embedded pok files in a POKES/ folder.

EDIT: Loading a pok file doesn't mean that all cheats are applied (could have incompatibilities), just are shown to the user.

**Comment by bog-dan-ro** [comment]
@windale yes, I think it might be possible ...
@sbaldovi I'm not using fuse routines to get the folder content :), so I'll need to hide them myself ...

**Comment by windale** [comment]
Or as it has just been said, search for the .pok files in a POKES folder. This will make the folders less sluggish as they will contain less files ?

**Comment by bog-dan-ro** [comment]
Uploaded a new version to google play beta channel and to github page https://github.com/bog-dan-ro/spectacol/releases
It contains all 3.0 closed issues (https://github.com/bog-dan-ro/spectacol/milestone/5?closed=1) + Sergio's auto boot patch

**Comment by ghost** [comment]
Thanks BogDan.
