### ISSUE TITLE
Disk icon bug

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#111]
If you load a SCL file, then while the disk icon is on screen, load a tape or .dsk file and the disk icon never goes away until you load another SCL file.

**Comment by bog-dan-ro** [comment]
I can't reproduce this bug :( please add two .scl files that I can use to reproduce the problem.

**Comment by ghost** [comment]
I can't reproduce it now either !

I'll close this for now. I seem to find these little things after a lengthy session (I also experienced that garbage text on the Pentagon screen again as well !)
