### ISSUE TITLE
Screen filter reset when selecting Timex

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#112]
At the moment, my filter of choice is 'TV 2x' but if you have to scroll through the Timex machines to get to a different Model then the filter is reset to 'Normal'.

**Comment by bog-dan-ro** [comment]
When you choose a timex machine I must reset all the filters because not all of them cam be used on a timex, that's why you'll loose the current model. I'll try to keep the current mode if possible

**Comment by bog-dan-ro** [comment]
Is not possible to use  TV 2X on timex that's why it resets to Normal

**Comment by ghost** [comment]
Well it would be better if it didn't change and reset the machine model when scrolling through the machine types. Highlight the machine you want to use then press a button to select it, it makes a lot more sense.
