### ISSUE TITLE
Doesn't handle Pokes correctly

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#114]
When going to the Poke Memory option it nearly always selects the first poke (when using external joypad), I think it's detecting button presses too quickly.

Some games have the pokes already enabled in the Poke Memory section but don't actually work, you have to turn them off then on again. For example, in the attached game four of the pokes are already active (ticked) when loading, this DOESN'T happen on Fuse.

[Poke test.zip](https://github.com/bog-dan-ro/spectacol/files/420842/Poke.test.zip)

**Comment by sbaldovi** [comment]
That's a tape. You must wait until the tape loading is complete before loading the poke file and check the memory contents. Sometimes this happen immediately, sometimes it's longer.

In Fuse, the poke file load is delayed until the user open the dialog. That's usually the proper time as sometimes poke files aren't needed and are a waste of resources.

**Comment by ghost** [comment]
What do you mean by 'That's a tape' ? You have to unzip it as Fuse/Spectacol only loads the first file in zip files (pointless IMO). The zip file contains a TZX and the POK file.

When I said 'when loading' I meant 'after it's loaded' obviously, there's no point poking memory before the game has loaded into memory. So basically Spectacol has to be told not to load the poke file until you go to the Poke Memory menu.

**Comment by sbaldovi** [comment]
I meant that with snapshots you usually have instant access to the final memory to poke. With a tape (TZX), the loading process isn't instantaneous. That was a hint to BogDan, because Spectacol use a thread for the emulated machine and other for the UI. I don't know certainly the internals of the file handler, but an early attempt to load the poke file could explain these symptoms.

**Comment by bog-dan-ro** [comment]
@sbaldovi thanks a lot for explanations! I'm moving pokemem_autoload_pokfile to the right place.

**Comment by ghost** [comment]
Does this also fix this minor thing ?

"When selecting the Poke Memory option it nearly always enables the first poke (when using external joypad), I think it's detecting button presses too quickly."

**Comment by bog-dan-ro** [comment]
Yep!
