### ISSUE TITLE
Using Sumvision Wireless Keyboard with touchpad causes issues on android tv box

### ISSUE THREAD

**Issue by deffstar72** [bog-dan-ro/spectacol#128]
Please accept my apologies in advance if this has already been raised but I have a Sumvision Wireless Keyboard that I use with my A95X 1GB/8GB android tv box.

What I've noticed is that if I use the touchpad to move the cursor, it enters a numeric character, I suspect it is using the Cursor joystick numbers and it will repeat them unless I swipe the touchpad in a different direction.

I thought about uninstalling and reinstalling the emulator to see if that would resolve it?

**Comment by bog-dan-ro** [comment]
No problem, it wasn't reported.
Can you please try to turn off the kempston mouse from Options->Peripherals and test again ?

Reinstalling it will not fix the problem :)

**Comment by deffstar72** [comment]
If I remember correctly I've turned them all off, just in case.

Thing I noticed is that it seems to default to the cursor joystick when I
load a new game even though I've disabled it.

**Comment by bog-dan-ro** [comment]
Should be fixed in v1.6.x.y, available now in beta channel.

**Comment by deffstar72** [comment]
Thank you :)

I've not used it for a long time but if I do, I'll certainly give it a go
