### ISSUE TITLE
Two problems

### ISSUE THREAD

**Issue by marca1969** [bog-dan-ro/spectacol#130]
Hi everybody,
I installed Spectacol today for using my Recreated ZX Spectrum keyboard on a Kraun tablet. The keyword works perfectly, but:
1) I cannot find how to save snapshots
2) tape recordings are not saved in the Recording directory.

Any ideas? Thanks!

**Comment by marca1969** [comment]
An addition:
I've seen that when closing a tape an "invalid parameter" error appears. May this be due to the file name that contains the ':' char? Unfortunately from my settings panel I can change the format of the date, but not that of the time. Whatever the format, the ':' are always used.

**Comment by bog-dan-ro** [comment]
* the "Recording" folder is for "RZX" recordings (e.g. record your walkthrough of a game)
* the saved snapshots should be located into "/sdcard/Spectacol/Snapshots" folder

**Comment by bog-dan-ro** [comment]
I'll check the ":" problem, though it works perfectly on my all Android devices.
Is it possible to give a step by step report that I can use to reproduce the problem?

**Comment by marca1969** [comment]
Here is a step-by-step procedure for the error message:

1) Start Spectacol (48k Spectrum, in my case)
2) Media/Recording/Start recording
3) type anything, for example 10 REM
4) SAVE “test” then press a key
5) media/tape browse shows that the program has been actually saved (both the header and the data block are shown)
6) stop recording

At this point the error message appears
