### ISSUE TITLE
Different 'trdos.rom' request and add Multiface roms

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#132]
Hi, thanks for updating this to the latest Fuse version. Could you swap the current baked trdos.rom 

v5.03 CRC32(10751aba) Fuse (formerly), Spectacol, ZXDS, R80, Unreal Speccy, Z80 Stealth (Beta128)

With this one please ? -

v5.03 CRC32(c43d717f) Spectaculator, SpecEmu, Zero, X128 and Z80 Stealth (Pentagon)

It has better compatibility with RZX files as proved here -

https://sourceforge.net/p/fuse-emulator/bugs/336/?limit=25&page=1#74d6

**Comment by ghost** [comment]
These multiface roms could be added too as some RZX files give an error that they are missing.

(4b31a971)    mf1.rom "MU 2.1, 1986"
(78ec8cfd)    mf128.rom "V36 DIS, 1987"
(2d594640)    mf3.rom "V50 MULTP3, 1987"

**Comment by bog-dan-ro** [comment]
I'm afraid I could not find those roms, can you please give a link or attach them to this bug report ?

Sorry for slow reply.

**Comment by blinkydoos** [comment]
Could you let me know when you've got them and i'll delete the file in case someone moans :)
[new.zip](https://github.com/bog-dan-ro/spectacol/files/1272882/new.zip)

**Comment by ghost** [comment]
I see you've added the Multiface roms in your latest commit. Could you also swap the 'trdos.rom' with the one I also provided as described in the first post above before you release the new version ?

**Comment by bog-dan-ro** [comment]
Can you please attach it here?

**Comment by ghost** [comment]
It's in the 'new.zip' attachment posted above.

**Comment by bog-dan-ro** [comment]
Then it's in the last commit :)

**Comment by bog-dan-ro** [comment]
https://sourceforge.net/u/bog-dan-ro/fuse/ci/8bab0a34753a11763caada763de2d5ded188511b/log/?path= 
https://sourceforge.net/u/bog-dan-ro/fuse/ci/8bab0a34753a11763caada763de2d5ded188511b/
?

**Comment by ghost** [comment]
OK, didn't see that, thanks. I'll close this.
