### ISSUE TITLE
Use Recreated Spectrum keyboard for all text entry

### ISSUE THREAD

**Issue by mcphail** [bog-dan-ro/spectacol#135]
Hi. Your support for the Recreated Spectrum keyboard is very welcome. However, if I have to use the keyboard for text entry in a normal android dialog (e.g. to the search bar) I have to switch the keyboard between the "Layer A" and "Layer B" settings. This can cause a flurry of random characters when switched back and forward. Would it be possible to modify the app to make it possible to keep the keyboard in "Layer A" for the search dialog etc?

**Comment by bog-dan-ro** [comment]
Sadly it's not possible as the keyboard sends it's keys directly to the system not to spectacol.
