### ISSUE TITLE
Show callstack with debug symbols enabled on crash

### ISSUE THREAD

**Issue by ohhmm** [bog-dan-ro/spectacol#136]
It crashed on launch on Philips Android TV. It would be nice to see why.

**Comment by reybits** [comment]
Connect your desktop computer to Android TV via wire or air (if possible) and run command ```adb logcat```.

**Comment by ohhmm** [comment]
[spectacol.log](https://github.com/bog-dan-ro/spectacol/files/1629324/spectacol.log)

**Comment by ohhmm** [comment]
beta works well

**Comment by bog-dan-ro** [comment]
OK, I'll promote it to production soon
