### ISSUE TITLE
Project ERROR: Unknown module(s) in QT: gamepad

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#138]
Hi,
I try to build spectacol in Manjaro, but when I open spectacol.pro with qtcreator I have this message : 

Project ERROR: Unknown module(s) in QT: gamepad

and the build fails.

Thank for your help.

**Comment by bog-dan-ro** [comment]
Well, as the error says, you need to install [Qt Gamepad](https://doc.qt.io/qt-5.9/qtgamepad-index.html) module. Be aware that Qt Gamepad is a **Technology Preview** module and most probably is not packaged by your distribution, I recommend you to install and use [Qt SDK](https://www.qt.io/download).

**Comment by ghost** [comment]
Thank you for your answer.
I have installed QT Gamepad, but now I have : 

/usr/bin/ld: /Téléchargements/build-spectacol-Desktop-Debug/spectacol/../desktop/lib/libspectrum.a(bzip2.o): undefined reference to symbol 'BZ2_bzDecompressEnd'
/usr/lib/libbz2.so.1.0: error adding symbols: DSO missing from command line
make[1]: Leaving directory '/Téléchargements/build-spectacol-Desktop-Debug/spectacol'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:339: fuse-qml] Error 1
make: *** [Makefile:45: sub-spectacol-make_first] Error 2
10:03:19: Le processus "/usr/bin/make" s'est terminé avec le code 2.
Erreur lors de la compilation/déploiement du projet spectacol (kit : Desktop)

**Comment by bog-dan-ro** [comment]
Hmm it seems it doesn't like your bzip2 dev files, add `--without-bzip2` to https://github.com/bog-dan-ro/spectacol/blob/master/build/desktop.sh#L56 and see if it works

**Comment by bog-dan-ro** [comment]
make sure you remove the build folder `/Téléchargements/build-spectacol-Desktop-Debug`, then try again.

**Comment by ghost** [comment]
ok, thank it works, but then I have this problem : 

$ ./fuse-qml

**
GLib:ERROR:ghash.c:377:g_hash_table_lookup_node: assertion failed: (hash_table->ref_count > 0)
Abandon (core dumped)
