### ISSUE TITLE
Online search not working

### ISSUE THREAD

**Issue by gingertips** [bog-dan-ro/spectacol#139]
Online search does not work. Type in a text string and search but no response returned

**Comment by bog-dan-ro** [comment]
It works just fine for me. Make sure you that what you type really exists.
Try: "renegade" or "turtles"

**Comment by gingertips** [comment]
Tried both of these  also wheelie but no response.  Is there a configuration somewhere maybe preventing it? It did work 2 days ago but now stopped working

**Comment by gingertips** [comment]
BogDan

I checked this again last night after you asked me to navigate to https://archive.org - which also didn't work. After some investigation, I found that it was because my mobile phone operator blocks websites with adult content!  A quick phone call to them to turn off that setting & all was fine again.  Thank you for help - I noticed in the reviews of the app that there were other comments about not being able to search online - it was probably the same issue.  Thanks
