### ISSUE TITLE
Latest version APK or GooglePlay

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#140]
Hi, is there any chance of putting the latest version on GooglePlay or an APK to download ?

**Comment by bog-dan-ro** [comment]
It quite unstable. 
I'll update the beta version in a few weeks from now after I'll fix some issues. 
Make sure you will click on "Become beta tester" if you want to try it.

**Comment by ghost** [comment]
OK thanks. That's weird because any version above v1.4.1 no longer works on RetroPie either.
