### ISSUE TITLE
Android 9, menu system etc disappears

### ISSUE THREAD

**Issue by corbym** [bog-dan-ro/spectacol#145]
On my Pixel 3 XL running Android 9, the menu system buttons disappear. Removing cache seems to help, but it happens again after a while.

I know you don't support Android 9 yet, but I thought you might appreciate the bug report anyway.

Great job with the emulator btw 😁

**Comment by bog-dan-ro** [comment]
Should be fixed in v1.6.x.y, available now in beta channel.
