### ISSUE TITLE
Spectacol online search using GPD XD

### ISSUE THREAD

**Issue by markythornton** [bog-dan-ro/spectacol#148]
Hi.
Absolutely love this emulator!
But I am having an issue which has stopped me playing it.
The online search feature stopped working all of a sudden some months ago.
I have tried uninstalling and reinstalling with no success.
It used to work perfectly.
If i search for any game it won't even try to search for it.
It just stays with the game title I have typed in on the search bar and nothing else.
Please help!!
I am a bit of a technophobe  so please bear with me!
WiFi is working fine.
Not sure if my device updated and somehow blocked it from searching?
Any help would be much appreciated so I can get back to playing my Spectrum games!!

Thanks

Marky T

**Comment by bog-dan-ro** [comment]
Hi,

Just checked the online search and it works perfectly here.
Please check (on the same network) if you have access to https://archive.org/ .
If you can't access it, please contact your ISP to unban archive.org.

**Comment by markythornton** [comment]
Hello again

Yes, i can access archive.org but it's still not working.
It works fine on my Samsung A10 on using the same ISP

Any more ideas please?

Thanks

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bog-dan-ro** [comment]
I'll need more information about your device:
 - name
 - what android version does it uses
 - does it have a browser or can you install one? If yes, please try to access https://archive.org/ on that device.

**Comment by markythornton** [comment]
Hi

It's a GPD XD

Android Version 4.4 4
Kernel V 3.10.0

I have both:-
Google Chrome V 81.0.4044.138
and this

[Image]

I can access 'achive.org' no problem using browser or chrome

Strange as Spectacol used to work perfectly, then just stopped online searching

[Image]



Thanks

Mark

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by bog-dan-ro** [comment]
I can't reproduce this issue.
