### ISSUE TITLE
Gamepad as kempston joystick doesn't work

### ISSUE THREAD

**Issue by pakr-info** [bog-dan-ro/spectacol#150]
I have an Android (Oreo 8 version) Philips TV with connected Logitech F710 and I have o trouble to use gamepad as kempston joystick. It looks like that joystick stick is permanently moved to right down position and fire button is pressed. When I move with left stick nothing is happened. When I switch joystick type as" cursor joystick" gamepad works well without any troubles. Also gamepad can be used for navigation (in menu, etc) of spectacol without any troubles. Of course Kempston joystick is enabled in Options - Peripherals.

Any ideas what is wrong?

**Comment by bog-dan-ro** [comment]
Check two things:
- make sure you select the joystick type also from Spectacol (as it doesn't know what you've selected in your game)
- try another game

**Comment by pakr-info** [comment]
Thanks for quick answer. I checked again and Kempston joystick is enabled Options-Peripherals, Kempston Joystick is selected in Joystick type and it is selected in for example JetPac game, but it works as I described. I tested with other games and same problem.

**Comment by bog-dan-ro** [comment]
I just tested the application with a PS4 controller and I had the same problem :). I'll try to fix before x-mas.

**Comment by bog-dan-ro** [comment]
Should be fixed in v1.6.x.y, available now in beta channel.
