### ISSUE TITLE
floating keyboard

### ISSUE THREAD

**Issue by zartan9** [bog-dan-ro/spectacol#151]
hi works great on my samsung droid..is there a way to float keyboard (a dos emulator has this option) or make the keys smaller/map just a few...its kinda blocking infront of the game!! Great software :)

**Comment by bog-dan-ro** [comment]
The keyboard keys size, in landscape mode, were designed with usability in mind. Making them smaller will not help.
In options - screen - screen orientation you can set it to Any which will allow you to use it in portrait mode (the keyboard will be below the emulator screen).
