### ISSUE TITLE
Support extra file formats

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#23]
RZX Replay support
SCL Support (with autoboot)
TRD Support (with autoboot)

I know regular FUSE already supports these so would love to see the Android version support them.

**Comment by bog-dan-ro** [comment]
I think it already supports them, do you have any example that doesn't work ?

**Comment by ghost** [comment]
1) To be honest, I only tried the standard google play version and I couldn't even navigate to where my files are. Is it even possible to change the game directory ?

2) I tried changing the model to something that supports SCL (Pentagon/Scorpion etc.) but it wouldn't let me.

3) I also got the sound warning when starting, what devices are actually supported for this ? I have a GPD XD handheld (Arm Mali).

I hope all these things can work on the next official release :)

**Comment by bog-dan-ro** [comment]
You can download the beta version by following https://play.google.com/apps/testing/eu.licentia.games.spectacol 
It also (optionally) allows you navigate everywhere (must be enabled from options->general)

**Comment by ghost** [comment]
I had a quick test of the beta version and SCL and TRD files don't work, it just resets to 48k. I haven't tried RZX replays yet. Only a few of the basic machine models work.

I also have a couple more requests, I would like the games list to remember where I got to in the list. If you have a lot of games you have to keep scrolling through from the beginning each time. Also annoying if you accidently push up while scrolling through and it changes directory !

An option to change the way the games list is displayed like a basic list mode, I can't always see the filename on the cover flow. And maybe a scroll bar so we can skip fast through the list.

**Comment by bog-dan-ro** [comment]
Can you share one of these files with me?

**Comment by ghost** [comment]
I got these from vtrdos.ru

I like these as there are no multi-loads and they come with trainers etc.

[SCL & TRD test.zip](https://github.com/bog-dan-ro/spectacol/files/210174/SCL.TRD.test.zip)

**Comment by bog-dan-ro** [comment]
It seems FUSE doesn't support these files (scl & trd) :( I tried them with fuse-sdl from debian packages.
Anyway I'll keep it open, maybe I'll have time to dig deeper.

**Comment by bog-dan-ro** [comment]
BTW, RZX should work just fine.

**Comment by ghost** [comment]
SCL work on Windows FUSE but you have to manually LIST the contents of the disk and LOAD"" the bootable file. That's why I requested 'autoboot' in the first post.

**Comment by bog-dan-ro** [comment]
I published a new beta which should fix this issue.
Please way a few hours until it's propagated by google.
