### ISSUE TITLE
Support Zip files

### ISSUE THREAD

**Issue by bog-dan-ro** [bog-dan-ro/spectacol#28]
I think it's better to browse the .zip file than to try to start first "loadable" file.

**Comment by ghost** [comment]
But only with zips that contain multiple files though right ? If it contains a single file it should just boot instead of browsing the contents.

**Comment by bog-dan-ro** [comment]
Yeah, though is quite unproductive/stupid to use zip to compress a single file :)
IMHO using gz,bz2,xz is a better choice...

**Comment by ZxAsSeMbLeR** [comment]
Yes it could be really nice to have the option of browsing inside zip files (as for example USP does). If there is only one file the idea would be to start it as windale suggests even if it is stupid to compress one file in zip format ;-), sometimes a lot of game collections are compressed that way.

**Comment by bog-dan-ro** [comment]
Fixed by upstream

**Comment by ZxAsSeMbLeR** [comment]
Is it only working with zip files with only one file in it, isn't it?. When there are multiple files zipped in the same file I can't browse it.

Anyway....good improvement! ;-)
