### ISSUE TITLE
Instant crash

### ISSUE THREAD

**Issue by RichyH67** [bog-dan-ro/spectacol#31]
I have an unlocked Asus TF300T running 6.01 and Spectacol doesn't even run. It crashes instantly on launch.

**Comment by RichyH67** [comment]
Should have mentioned it's rooted and using KatKiss 20163103 CFW. I see the splash screen for a second then it crashes.

**Comment by bog-dan-ro** [comment]
I'll need the log from your device when it crashes.

Please run :
 $ adb logcat -c
 $ adb logcat

Then start Spectacol, wait until it crashes, copy the output of adb logcat and send it to me.

**Comment by RichyH67** [comment]
After rebooting the tablet, this crash has yet to reoccur. It might have
been an issue relating to the recently installed CFW. If the crash returns,
I will try and capture a log file for you.

On 11 April 2016 at 09:15, BogDan Vatra notifications@github.com wrote:

> I'll need the log from your device when it crashes.
> 
> Please run :
> $ adb logcat -c
> $ adb logcat
> 
> Then start Spectacol, wait until it crashes, copy the output of adb logcat
> and send it to me.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/bog-dan-ro/spectacol/issues/31#issuecomment-208219933

## 

Richard H.

**Comment by bog-dan-ro** [comment]
ok, I'll close it for now, if it happens again please reopen it
