### ISSUE TITLE
Scale to fit the screen

### ISSUE THREAD

**Issue by bog-dan-ro** [bog-dan-ro/spectacol#33]
It's useful when you are using external controls

**Comment by ZxAsSeMbLeR** [comment]
Thanks for implementing this!. Maybe the possibility of choosing the size of the border (for example, none, small or medium) when stretching to fill screen would be also interesting.

**Comment by bog-dan-ro** [comment]
Sadly FUSE doesn't support the possibility to choose the border size ..., but it should not be hard to implement scale to fullscreen mode

**Comment by ZxAsSeMbLeR** [comment]
Thank you! Great improvement to the emu!
