### ISSUE TITLE
Error writing to sd already downloaded online games

### ISSUE THREAD

**Issue by ZxAsSeMbLeR** [bog-dan-ro/spectacol#36]
This is a minor bug, but anyway here it is:
- When you play an online game and the game is copied to favourites folder (and downloads cache folder) and later you try to play that game again using the online browser, the emu says it can't copy that game and the game doesn't start (obviously, that is because the emu neither replaces the already downloaded game nor starts the local file).

Yeah, is something we can live with, but I thought it would be interesting to let you know ;-)

Thanks!

**Comment by bog-dan-ro** [comment]
Thanks!

**Comment by bog-dan-ro** [comment]
Fixed, if you want to test it please use https://play.google.com/apps/testing/eu.licentia.games.spectacol to become a beta tester, wait a few hours until google play will make the change visible to everyone.

**Comment by ZxAsSeMbLeR** [comment]
Thanks for fixing in the new version!
