### ISSUE TITLE
Tape Browser

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#38]
A way to view the files on the cassette. Some tapes have more than one program on them so if we could select where to start the tape from or if we have to rewind a bit because of a multi-load level etc.

Is this emulator still going ? No new commits in over a week ? (Just curious). EDIT. Just noticed your reply on the SCL autoboot issue.

**Comment by bog-dan-ro** [comment]
Yes, It is still going!
I just waiting for feature requests to settle down, then I'll peek the most important ones for next major release, and then I'll start to implement them.

One more clarification:I'm doing this in my free time (when I have it), so there will be only rough release dates.

Of course everyone who can help, is more than welcome to join the development ;-)

**Comment by ghost** [comment]
I have had a quick go on the new beta and it is feeling very nice. There are only about 5 more major things (in my personal list) and this will be my favourite Spectrum emulator (plus some minor things which will be a bonus).

So what is the actual use of the 'Open Tape' menu currently ?  The rewind tape option I'm not sure how much its rewinding, or does it just go back to the beginning ? I suppose this will be more useful when we can visually see the file blocks on the tape and have the option to choose what block to start playing the tape from. This way we can rewind multi load games back to level 1 and choose what game to load on compilation tapes. This is one of the Nintendo DS emulator ZXDS's great features.

Just in case you wanted to know the major features I'm looking forward to : 

The tape contents browser I just talked about.

SCL files autoboot. Unfortunately the FUSE team haven't added anything on this yet. It seemed like an easy thing for programmers to add but obviously not.

An option to choose a basic and easy to read filelist.

Getting rid of everything on screen during gameplay when using physical controls except for the tape/disk images when loading.

Option to map buttons to Spectrum keys, like making one of the buttons press Space as this is commonly used.

Everything else would be a bonus, like much better RZX compatibility (with progress percentage).

Thanks.

**Comment by ghost** [comment]
Is there any chance this can be increased in priority ? As someone already pointed out on the WOS forum, the tape browser is already present in Fuse, so wouldn't it be fairly quick/easy to port it to Spectacol ? I'm not worried about saving using the tape browser, I would just like to be able to see the currently inserted tape contents where you can choose what block to start the tape playing, just like Fuse.

**Comment by bog-dan-ro** [comment]
Yep, I think is doable in 3.0

**Comment by ghost** [comment]
Thankyou, I'll look forward to your next release.

**Comment by ghost** [comment]
Excellent work, I'll just let you know that long tapping on the tape contents only works with the touch screen, it doesn't work with joypad.

**Comment by ZxAsSeMbLeR** [comment]
Very nice tape browser!. Way better than Speccy's one. I have tried it with some magazine TZXs. Good job!! Just a possible improvement (to make it even better) would be the possibility to start a selected block directly (resetting the emu and auto-loading the block selected) within the browser.

**Comment by bog-dan-ro** [comment]
@windale that feature is only for touch screen device, I tried to make it work for gamepad but (at least for the moment) is not easy to do it / possible.

@ZxAsSeMbLeR might be, create a new issue and I'll see what I can do.

**Comment by windale** [comment]
> Just a possible improvement (to make it even better) would be the possibility to start a selected block directly (resetting the emu and auto-loading the block selected) within the browser.
@ZxAsSeMbLeR 
But that would take away the real Spectrum experience of typing LOAD"" (if on 48k) :). If it's on 128k just select the tape block, reset and press enter.
