### ISSUE TITLE
Android TV (Nexus Player)

### ISSUE THREAD

**Issue by reybits** [bog-dan-ro/spectacol#39]
Hello,

Please improve Android TV and GamePad support. At this moment I can't open emulator menu, can't select hardware and other stuff.

**Comment by bog-dan-ro** [comment]
Hi,
I need more information on this matter:
- what kind of gamepad do you have?
- does it have  "Start", "A", "B", "X", "Y"  buttons?
- does the gamepad works with other apps/games?

**Comment by reybits** [comment]
1. GamePad that shipped with Nexus Player. GamePad brand name is ASUS ( https://store.google.com/product/gamepad_for_nexus_player?sku=nexus_player_gamepad&gl=US )
2. With A, B, X, Y, Back and Home buttons, two analog joystics and one d-pad.
3. Yes, it works fine.

**Comment by bog-dan-ro** [comment]
Ah, it doesn't have a Stat button... I'll try to find another button to toggle the menu.

**Comment by reybits** [comment]
Almost each gamepad has 4 buttons under forefingers (L1, L2, R1, R2). Both joysticks has "four" directions and can be pressed down.

**Comment by bog-dan-ro** [comment]
I know, that's way I pushed a fix to https://github.com/bog-dan-ro/spectacol/commit/64318105699cd84692445b1562fac9e1702c57de :) but I think I'm going to revert it because L1 is already used in other places, so I think I'll use "Back" button instead.

**Comment by reybits** [comment]
Key Y opens onscreen keyboard. I think that is good place for menu button too.
Key X opens "digits" - another good place for menu button.

**Comment by bog-dan-ro** [comment]
X and Y are used in other places which will complicate things... I think I'll stick with "Back" button.
In the next major version I'd like to implement https://github.com/bog-dan-ro/spectacol/issues/6 which will allow you to assign actions to any button you like.

Anyway I hope tonight to fix it and I'll publish it to [beta](https://play.google.com/apps/testing/eu.licentia.games.spectacol)  for you to test it on your device.

**Comment by reybits** [comment]
Sounds good, thank you.

**Comment by bog-dan-ro** [comment]
Fixed, if you want to test it please use https://play.google.com/apps/testing/eu.licentia.games.spectacol to become a beta tester, wait a few hours until google play will make the change visible to everyone.

**Comment by bog-dan-ro** [comment]
@andreyugolnik  is the gamepad working now? You can open the menu using back button, right?

**Comment by reybits** [comment]
Yes, I can access to menu via Back button on GamePad.

**Comment by bog-dan-ro** [comment]
I just move it in production, if everything is ok, can you please update your review on Google Play?
Thanks!
