### ISSUE TITLE
Crashes sometimes when scrolling through Machine Type too quickly.

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#42]
As the title says, I held my finger down to scroll quickly to a Machine Type at the bottom of the list (Pentagon/Scorpion) and it crashed.

**Comment by bog-dan-ro** [comment]
I can't reproduce it yet ...

**Comment by ghost** [comment]
If you're near the top of the machine list and hold down on the d-pad to go to the bottom of the list (or vice versa) sometimes it crashes and says 'Unfortunately, Spectacol has stopped.'. To reproduce, just be near the top of the Machine types and hold the 'Down' key until it crashes. Not a big problem, i'll just have to remember not to scroll too fast.
