### ISSUE TITLE
Proper media (Tape & disk) support

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#43]
I turned off all the turbo loading options just to see the authentic tape loading in real time with loading sound and it still loaded quickly.

**Comment by bog-dan-ro** [comment]
Ah, that option is for another way to load the files that I didn't implement yet in Spectacol.

**Comment by windale** [comment]
Some games are nice to see loading at the correct speed, in particular the Alcatraz protection which made the loading screen come up in a fancy way.

**Comment by ghost** [comment]
In the latest version, if you turn off all the turbo load options games don't load at all.

**Comment by bog-dan-ro** [comment]
Spectacol needs to add proper support for ZX Spectrum Tape & disks

**Comment by bog-dan-ro** [comment]
It also needs upstream fixes https://sourceforge.net/p/fuse-emulator/bugs/346/

**Comment by bog-dan-ro** [comment]
Basic tape manager was added. Recording and write operations are postpone for future versions.

**Comment by ghost** [comment]
It doesn't effect me but I think that people without touch-screens are not going to be able to touch the cassette image to turn on fast loading.

**Comment by bog-dan-ro** [comment]
The 3 level loaders types are doing a better job
