### ISSUE TITLE
Adding a Forward Button to increase speed

### ISSUE THREAD

**Issue by ZxAsSeMbLeR** [bog-dan-ro/spectacol#44]
Hello!

I think it could be interesting to add a Forward Button to increase speed of execution while pressed. It is present in other emus and is very useful sometimes to accelerate a game execution in certain moments.

If in the future there's a working option for loading games at real time, this button could be useful to see the loading of the game but accelerated (yes...I admit I like to see the loading of a game but in 20 seconds instead of 5 minutes ;-))

Regards and thanks for your effort!

**Comment by ghost** [comment]
I think this request was mainly for a Fast Forward button that speeds up the gameplay (to skip through long text intros / RZX replays etc) and not the actual fast load option. Unreal Speccy Portable has a Fast Forward button that speeds up the whole game when held down, not just the loading.

**Comment by bog-dan-ro** [comment]
Fast Forward button will be added in a future version

**Comment by ZxAsSeMbLeR** [comment]
Good addition! and for version 2.0!!.

Just one question regarding this.: is it also working when loading a game at normal speed?. When I press the button loading a TZX in normal speed just to increase the loading speed but looking at the loading process just to "enjoy it" the speed remains the same and the sound dissapears. Is it a matter os processing speed?

## Thank you!!

**Comment by bog-dan-ro** [comment]
It works everywhere, as long as you keep it pressed the speed it increases to 10000%(x100), of course none of the existing android devices can increase the speed that much, but high end devices can do ~1000% (x10 speed).
