### ISSUE TITLE
Make SCL files auto-boot

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#46]
I thought i'd open a seperate issue for this as you closed the other one (which was really two issues) and auto-boot is still not implemented.

**Comment by ghost** [comment]
Did they give you any code to get this working ? They have talked a lot about it and never got any further than the "press enter twice" workaround. I'm not sure if it's still going ahead or they are waiting for input from someone.

**Comment by bog-dan-ro** [comment]
Not yet.
Talking a lot about it it's a good sign, it means people are involved and they're searching for the best solution. This is how free software works ;-)

**Comment by bog-dan-ro** [comment]
https://sourceforge.net/p/fuse-emulator/feature-requests/90/

**Comment by ghost** [comment]
I have been very impressed with your work on this emulator, the last few features you knocked out very quickly. Are you sure YOU can't add this autoboot feature for them ? When I read some of your replies on the FUSE source forge page it seemed like you knew more than them !

**Comment by bog-dan-ro** [comment]
Sadly, it's an area where I have almost no idea how it works, therefore we need to be patient until the right guys will fix it ;-).

**Comment by bog-dan-ro** [comment]
Sergio made good progress on this issue, if you have time please take a look to https://sourceforge.net/p/fuse-emulator/feature-requests/90/ . You'll find also a link to spectacol .apk which contains that patch.

**Comment by ghost** [comment]
I tried your new .apk with this feature and found it a bit sluggish ? When opening and closing the side menu it stutters and the known problem about the sound whining when changing game. I also think the sound might be lagging (small stutters) on the games, i'm not sure as i've only tested it quickly.

**Comment by bog-dan-ro** [comment]
It's my bad, I used a debug qt version :) when Sergio will push the fix I'll push a proper APK to google play beta channel.

**Comment by bog-dan-ro** [comment]
Fixed by upstream
