### ISSUE TITLE
Gamepad doesn't work on the New MAIN menu.

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#50]
Add a reset calibration button

**Comment by bog-dan-ro** [comment]
It might happen when you calibrate the gamepad and you didn't select the "Start" button properly.
To reset to default just open again the calibration press back button on your device or be careful when you choose the buttons.

**Comment by ghost** [comment]
I reset the controls and configured again, but it's still the same. The 'Start' button opens the main menu but I can't move up and down with the joypad.

**Comment by bog-dan-ro** [comment]
Strange ... please reinstall the application

**Comment by ghost** [comment]
Uninstalled and re-installed. Joypad still doesn't work on the Main menu, It does work in game and when selecting machine type. (On the plus side, 16K, 48K and 48K NTSC now work properly).

**Comment by bog-dan-ro** [comment]
Does it work on other android apps? Can you use d-pad or left joystick to select apps for your android launcher?

**Comment by ghost** [comment]
Yes the joypad works on the Android launcher. The joypad used to work on Spectacol on the main menu before the 2.0 Alpha update.

**Comment by bog-dan-ro** [comment]
Odd ... I'm pretty sure I didn't touch that part.
Anyway, I'll check it again these days (maybe tonight).
