### ISSUE TITLE
Some machine types don't work.

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#51]
The 48k models don't work properly, the keep booting to TRDOS.

**Comment by bog-dan-ro** [comment]
I need more info on this matter (e.g. steps to reproduce it). 
I just tested to select 48k and 48k (nstc) machines from "Machine->Select ..." manu and they work just fine for me.

**Comment by ghost** [comment]
There must be something weird going on. If I select 16K, 48K or 48K NTSC they all reset to the TR-DOS prompt.

**Comment by bog-dan-ro** [comment]
What version are you using ?

**Comment by ghost** [comment]
It says 2.0 alpha 1

**Comment by ghost** [comment]
Uninstalled and re-installed and they work correctly now.

**Comment by bog-dan-ro** [comment]
ok, I'll close it for now, if it happens again please reopen it

**Comment by ghost** [comment]
Can't choose 16/48k models again, it boots to TRDOS. Even when I close and re-open the app, they seem to have stopped working completely.

**Comment by bog-dan-ro** [comment]
I'll need a way to reproduce it ...

**Comment by ghost** [comment]
16k/48k models are permanently TR-DOS now, i'll have to uninstall and re-install and try to reproduce.

**Comment by ghost** [comment]
OK, I think I can reproduce. Select Scorpion model (dont scroll too fast or it crashes, may also work on Pentagon as it's also TRDOS) and load a TZX. Go back to the change model list and 16k/48k are now TRDOS. You will then need to uninstall and reinstall to get them back.

**Comment by ghost** [comment]
Also happens when selecting Pentagon 128 and loading a TAP file.

**Comment by bog-dan-ro** [comment]
Found the problem, and I upstreamed the bug to https://sourceforge.net/p/fuse-emulator/bugs/342/
We need to wait for FUSE devs to check what's the best way to fix it
