### ISSUE TITLE
Smooth scaling

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#52]
It still looks the same as before, some thin lines, some thick. 'Preserve aspect' looks OK but obviously smaller screen.

**Comment by bog-dan-ro** [comment]
As the name says it fits the width/height of screen, therefore it can't use fixed scaling (1x, 2x, 3x, ...) meaning that you can't get a perfect scaling using this scaling method.

**Comment by ghost** [comment]
Could you add an alternate scaling method so it looks correct, like Unreal Speccy Portable and Spectaculator ? Playing on a handheld gaming device (with built in controls) the screen was small to begin with ! Without scaling it's tiny !

**Comment by bog-dan-ro** [comment]
You have "Preserve aspect" which uses fixed scalling

**Comment by bog-dan-ro** [comment]
It is impossible to scale 256 lines to 800 without having thin and thicker lines :)

**Comment by ghost** [comment]
Just out of interest, how do the other emulators achieve it ?

**Comment by bog-dan-ro** [comment]
It is had to say how (or if) they do it as long as I don't have access to their source code.
If you have time you can do a test by taking a screenshot of e.g. 128k boot image using all of these emulators and check every line and add the screen images to this bug report.

**Comment by ghost** [comment]
I just checked Spectaculator Android and it has the same bad scaling but it has an option called 'pixel smoothing'. Could you add this to Spectacol because none of your filters have the same effect. It's something like Bilinear.

**Comment by bog-dan-ro** [comment]
I'm already using bilinear for scalling check: https://github.com/bog-dan-ro/spectacol/blob/master/fuse/ui/qml/fusetexture.cpp#L130 maybe nearest will be better ...
Please add some screenshots to have a reference

**Comment by ghost** [comment]
![screenshot_2016-04-25-15-41-30](https://cloud.githubusercontent.com/assets/12862298/14787688/65cd9b42-0afc-11e6-8486-977f6522d156.png)

**Comment by bog-dan-ro** [comment]
Wait a minute, I just checked UPS and Spectaculator so called "pixel smoothing'". It's anything but pixel smoothing. It's just an ugly blurring which gives you the impression that it looks better... 
If you take a closer look you'll see that there are still thin and thicker lines.

IMHO AdvMAME or HQ + linear scaling is way much nicer than an ugly blurring.

**Comment by ghost** [comment]
Back in the day the picture was slightly blurred like this with scanlines. That's what pixel smoothing is. At the moment if you use 'preserve aspect fit' it has an aliased LEGO effect.

**Comment by bog-dan-ro** [comment]
It has an aliased Minecraft effect ;-)

**Comment by ghost** [comment]
Hi, could you increase priority of this because currently it looks terrible and is the only Spectrum emulator that doesnt have the option. Marvin, Speccy, USP and Spectaculator all can do this. I dont know if you have lost interest in this emulator ? I hope not. Thanks. And its not exactly blurry, its the way its meant to be played :)

**Comment by ghost** [comment]
Thanks, you made a minor spelling mistake, 'scaling' only has one 'l'.

Is there any sort of guess as to when the next beta/2.0 will be released ?

**Comment by bog-dan-ro** [comment]
Thanks for checking it.
I hope tonight/tomorrow to publish a new alpha

**Comment by windale** [comment]
Can we have 'Preserve aspect fit' and smooth scaling please ? The option has disappeared. I thought the point was to have the smooth scaling with a full screen image (at correct 4:3 aspect).

**Comment by bog-dan-ro** [comment]
It doesn't seem to work properly on my Android (when it's checked is not smooth)

**Comment by ghost** [comment]
I had a similar problem. If you keep pressing it it does eventually decide to turn on ! (But normally goes smooth when the option is unchecked !)

**Comment by bog-dan-ro** [comment]
strangely on desktop it works just fine ...
