### ISSUE TITLE
Doesn't remember scrolled position properly in the game list.

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#53]
I think it only remembered the first time and now it keeps going back to the first game I loaded and not the most recent one.

**Comment by bog-dan-ro** [comment]
The positions are saved for the application lifetime, if you quit the application these positions are lost.
Also only the local file browsing saves the positions.

A step by step example will help me better to understand the problem.

**Comment by ghost** [comment]
I put my games in alphabetic folders (because it took forever to scroll to the required game). If I go to the B folder I have 'D.N.A. Warrior' as the first game in the list. If I go forward a bit and select 'Danger Mouse'. When I go back to select a different game it's gone back to 'D.N.A. Warrior' again (the beginning of the list).

**Comment by bog-dan-ro** [comment]
Ah, I don't save the positions only when you change the folder :) 
Good catch!

**Comment by ZxAsSeMbLeR** [comment]
Maybe I have made something wrong, but when trying the new features of the yesterday released beta, I have noticed that the emu doesn't remember the position of the last opened file loaded locally (it was working in the previous version). I will make more testing on this

Thank you!

**Comment by ZxAsSeMbLeR** [comment]
Yes, in last release it is working again.

Thank you!
