### ISSUE TITLE
Auto Applying Current Joystick Selection in Games

### ISSUE THREAD

**Issue by ZxAsSeMbLeR** [bog-dan-ro/spectacol#59]
Hmmm, I think we talked about this on World of Spectrum forum. You explained that each z80 has its own default control selection and that's the reason why even if you choose Kempston, for example, in the emu joystick selector, the option is changed sometimes when loading a new z80 game. Maybe, instead of showing the selector after loading a new game, it could be possible to automatically change the joystick type to the current default selected joystick in the emu after loading each game.

I think that would be better because if you select kempston and change games you only have to choose Kempston in each game to have the controls responding, and not feeling the controls are not responding and then...Go to menu...select joystick and put kempston again....a lot of times when a new game is loaded.

Maybe auto applyng current joystick selection would be really nice by default or at least as an optional check.

Thanks!!. Hey...Maybe a donation option for all your hard work and for listening all our suggestions and sometimes crazy ideas ;-), would be interesting. I would donate some euros for sure.

**Comment by bog-dan-ro** [comment]
I'll need to check if FUSE engine supports it and if it is, it will be a trivial change.
Otherwise it will take some time, first I'll need to check if FUSE developer are ok with this kind of change, then change FUSE itself, then wait for upstream to integrate it and then merge the changes. I want to upstream everything because I don't want to maintain all these patches myself ;-)

Regarding the donations, as I said I'm not doing this for the money (that's why as long as I'll runt this project you'll not see any ads in it) but because I like what I'm doing and also because I didn't found an emulator that I can play my old games on all my android devices.

**Comment by ZxAsSeMbLeR** [comment]
Hmmm....I see...As you can change controls using the menu anytime in the middle of a game and that works, I thought you can force changing controls after loading the game (as if a user had used the menu option) and assign automatically the default controlller selected. Let's hope it's and easy change and doesn't require changes in FUSE itself ;-). Otherwise, it's another story...

I know you are with this project becase you really like it. It was a suggestion just to invite to a pair of beers for your great work ;-)

Thank you!

**Comment by ZxAsSeMbLeR** [comment]
I have been betatesting this (changing from one z80 to another) but the joystick prompt screen is not appearing (even if the control changes). Anyway, I don't know if the change is already implemented in the last beta released yesterday or if it is for the next beta. 

Thanks for the addition!

**Comment by bog-dan-ro** [comment]
It should be implemented, can you share some z80 files that I can use to test it ?

**Comment by ZxAsSeMbLeR** [comment]
Yes, I will try to upload to dropbox some of them which don't start with kempston (which is the one I usually use) and share the link this evening at home.

**Comment by ZxAsSeMbLeR** [comment]
Here its is:

https://www.dropbox.com/s/z7nkl1rtjqkqwef/Examples.zip?dl=0

These two games are in z80 format. Before loading any of them I have Kempston selected. After loading my current selection changes to Cursor Joystick, but the selector screen is not launched after opening the game. It happens with lots of examples. These are two of them chosen ramdonly.

Thanks!!

**Comment by ZxAsSeMbLeR** [comment]
Hmmm...The joystick dialog is still not appearing. I have tried again several z80 after last update and it is not showing. I have tried in some devices (I have seen in your comments the problem may arise in showing the dialog but closing inmediately so you have inserted a delay to avoid fast press/unpress sequences).Is it working for you know?. Thanks for last beta releases!

**Comment by bog-dan-ro** [comment]
It works perfectly for me (at least with your two examples and some of mine).
Did you checked "Snapshot joystick prompt" option?

**Comment by ZxAsSeMbLeR** [comment]
Yes, now it works!. You are right. It was just I have not checked that option (I didn't know it was there!).
After checking that it is working perfectly. Sorry for my mistake and thanks for explaining.

Thank you. The emu is getting better day after day ;-)
