### ISSUE TITLE
Add a way to customize the gamepad buttons

### ISSUE THREAD

**Issue by bog-dan-ro** [bog-dan-ro/spectacol#6]
There are two tasks here:
- customize HW gamepad buttons
- customize the virtual joystick buttons

**Comment by ghost** [comment]
As you dont have time for this would it be much trouble to just make one of the joypad buttons act as the 'spacebar' ?. Just asking on the offchance.

**Comment by bog-dan-ro** [comment]
If Qt 5.7 release will be delayed to next week, I'll try this weekend to implement it and ship it with 2.0

**Comment by bog-dan-ro** [comment]
Moved to v2.0 due to popular requests.

**Comment by ghost** [comment]
Could you also add L3 and R3 as customizable buttons for those of us that have them ?

**Comment by bog-dan-ro** [comment]
Unfortunately L3 & R3 are not standard and are not handled by Andriod https://developer.android.com/reference/android/view/KeyEvent.html nor by QtGamepad module http://code.qt.io/cgit/qt/qtgamepad.git/tree/src/plugins/gamepads/android/src/qandroidgamepadbackend.cpp?h=5.7 so, in this moment is not possible to add those buttons
