### ISSUE TITLE
Reading POK format files and/or adding a poke manually

### ISSUE THREAD

**Issue by ZxAsSeMbLeR** [bog-dan-ro/spectacol#60]
Just thinking about more possible enhancements for this superb emu, maybe loading .pok files could be an interesting addition for the future. 

Moreover, I have not found a way to add a poke manually. Yes, there is a debugger and an option to help finding pokes, but if you have a poke and want to add it to the current loaded game I haven't find a way to do it.

Thanks!

**Comment by ZxAsSeMbLeR** [comment]
Great!! I will try as soon as a new beta is released ;-)

**Comment by bog-dan-ro** [comment]
Next alpha release will be out next week(end). It will be still alpha because the chances to implement all the remaining features for 2.0 release until next will are close to 0 ;-)

**Comment by ZxAsSeMbLeR** [comment]
Very nice addon to the emulator. Already trying it  ;-)
