### ISSUE TITLE
Some tapes dont load properly in 'Quick Open'

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#61]
Some tapes dont load properly when using 'Quick Open'. I think we need that 'Safe acceleration' option that was talked about here :  https://sourceforge.net/p/fuse-emulator/bugs/346/

**Comment by bog-dan-ro** [comment]
Can you share some of these files?

**Comment by ghost** [comment]
There are a lot that don't work with 'Quick Open'. Here's just a few I found quickly from the 'B's'. Also I think all games with Alkatraz Protection fail to load.

NOTE: This is with 'Detect Loaders' turned off.

[Quick Open Test.zip](https://github.com/bog-dan-ro/spectacol/files/266587/Quick.Open.Test.zip)

They seem to work fine with 'Detect Loaders' turned on. Probably just have to keep this option on all the time.

**Comment by ghost** [comment]
Yeah, I think we can just leave 'Detect Loaders' on permanently. Loading from the 'Tape' menu still plays at normal speed with this option on (and both methods can be speeded up by pressing the tape icon).

I think you can close this issue.

**Comment by ghost** [comment]
I found one game that needs 'Detect Loaders' turned off called 'SPLATTR'.

**Comment by ghost** [comment]
'Switchblade' doesn't load with 'Detect Loaders' turned on. When turned 'off' it takes a long time to load (the PC version loads it almost instantly) and if you press the tape icon to speed it up you get 'Tape Loading Error'.

**Comment by bog-dan-ro** [comment]
Please share Switchblade

**Comment by ghost** [comment]
[Switchblade (1991) (Gremlin Graphics Software).zip](https://github.com/bog-dan-ro/spectacol/files/268669/Switchblade.1991.Gremlin.Graphics.Software.zip)

**Comment by ghost** [comment]
Weird things are happening, now Switchblade doesn't load with Detect loaders off. When detect loaders is on does it only turbo load for 4 seconds like when you press the tape icon ? Because it loaded the first part quickly until the Switchblade name comes up and then it goes to normal speed.

**Comment by bog-dan-ro** [comment]
I'm going to use Fredrick's suggestion and have a 3 level option for loader acceleration (none, safe and turbo)

**Comment by ghost** [comment]
OK. It loads fine on the PC version and loads very fast. With all these options ON : 
Use tape traps
Fastloading
Detect loaders
Accelerate loaders

**Comment by bog-dan-ro** [comment]
The only problem I've seen is when using "safe" mode and hitting enter key after first screen is loaded.
If I don't touch any key it works ok.

**Comment by ghost** [comment]
Hitting the enter key ?

**Comment by bog-dan-ro** [comment]
I hit space

**Comment by ghost** [comment]
Only a minor thing but I just noticed that the game 'Vixen' doesn't load with any fastloaders. It works on PC Fuse when tape traps is turned off and all fast loaders on.

In Spectacol you can sort of get by this by loading with fastloaders off until it gets past the multi-coloured borders, then turn fastloaders back on. Protection scheme (SpeedLock 6). All SpeedLock 6 games work in Spectaculator (Fast Load).

[Vixen (1988) (Martech Games) (Side A).zip](https://github.com/bog-dan-ro/spectacol/files/270096/Vixen.1988.Martech.Games.Side.A.zip)

**Comment by ghost** [comment]
I've replaced all the SpeedLock 6 games in my collection (there were only 6 ever released) with different versions. No need to worry.
