### ISSUE TITLE
Weird things happen with on-screen keyboard

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#63]
I tried a few games then suddenly I couldn't figure out why it wouldn't let me press any keys. I reset to 48k basic and the on-screen keyboard didn't work. I closed Spectacol and ran it again, started pressing some keys and after a while it sometimes wouldn't type the key I was pressing and sometimes it just started repeating the key like it was being held down.

**Comment by ghost** [comment]
I can reproduce. It's easy to see in 48K Basic. If you move the on-screen keyboard key highlight while the button is pressed it keeps repeating the key on it's own (maybe forever ?). This is probably why I couldn't press any keyboard buttons during a game. Seems like a major bug.

**Comment by bog-dan-ro** [comment]
Thanks!
