### ISSUE TITLE
RZX files that require Z80 snapshots

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#64]
Some RZX files require you to select the game Z80 file before they will play. It comes up with an old FUSE requester that can't be used. It then won't let you load anything else and locks up when you quit. Here is a picture of what comes up when asked to load the accompanying Z80: 

![screenshot_2016-05-19-23-18-45](https://cloud.githubusercontent.com/assets/12862298/15411580/de994a92-1e18-11e6-8772-40e2eb16fa86.png)

**Comment by bog-dan-ro** [comment]
A such .rzx file will be quite useful.

**Comment by ghost** [comment]
Oops, I forgot to post the file !

[RZX Test.zip](https://github.com/bog-dan-ro/spectacol/files/274231/RZX.Test.zip)

**Comment by ghost** [comment]
I just sneakily tried your 3.0 alpha 2 and when trying to load a RZX that requires an external snapshot it gives the error 'RZX frame is longer than 79000 tstates' and locks up. (The 'RZX Test.zip' above used to work).
