### ISSUE TITLE
Pause function

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#67]
A button or option we can map to a button to pause the emulation and not alter the image. Particularly useful when reading text on RZX files, we can pause it to read before they skip too fast. Maybe add a pause icon. Thanks.

**Comment by ghost** [comment]
Just out of interest, are you waiting for FUSE 1.2 before you release the next version/beta of Spectacol ?

**Comment by bog-dan-ro** [comment]
Yes, I'd like to use 1.2 for the next alpha release, to have enough time to check it properly

**Comment by bog-dan-ro** [comment]
Will be covered by #6
