### ISSUE TITLE
Use own screenshots as game preview image

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#70]
An option to put our own PNG files (named the same as the games) into a different folder that will display instead of the generated ones. Most of my games are in TZX format and Spectacol can't extract the loading image on most of these so i'm left with a picture of a cassette (why is the cassette upside down ?). I have PNG files for all my games that show an in-game screenshot which is better for me because I can actually see what the game looks like and not just the loading screen.

**Comment by bog-dan-ro** [comment]
Spectacol extracts all the screens from most of the ZX formats (tzx and pzx for sure are one of many supported). Probably most of your TZX files has no loading screen(s), this is the reason why .Spectacol can't extract it.
Anyway, I'm working on something even better (I hope), which will allow you to add, not only screens, but also pokes & info, and many more things.

Keep an eye on #34

**Comment by ghost** [comment]
1) Where would it be pulling the information from, World of Spectrum (which has been under maintenance for over a year now) ? But this would mean I would have to be online.

2) Most of the TZX games that don't display an image definitely have loading screens, i've just checked.

3) How come you decided to put the cassette image upside down ?

**Comment by bog-dan-ro** [comment]
1. There will be multiple sources, one will be online (probably not WOS because, as you said their online service is dead for a long time), the other one will be you :). It will allow you to edit the metadata from within Specatcol. Of course if you wish you can also upload your changes, so, everyone will be able to use them.
2. Strange, please share one of these TZX files and I'll check it.
3. this is how I found the SVG image, I'll check if I can flip it :)

**Comment by ghost** [comment]
I checked through some (there are a lot) and I think that most of the loading screens don't display because of custom loaders/protection schemes.

**Comment by bog-dan-ro** [comment]
Well, that's another story, if I can't detect it I can't show it

**Comment by ghost** [comment]
And that's the reason why I asked if we could add our own images.

I've had the odd time when all the images in the file list disappear from the left side of the screen but not as bad as it used to be.
