### ISSUE TITLE
Online search

### ISSUE THREAD

**Issue by bobv46** [bog-dan-ro/spectacol#72]
Hey was playing your emulator and searched some 128k games .brilliant . Went on again later and search not working ?

**Comment by bog-dan-ro** [comment]
The search works ok.
Please check your internet connection.

**Comment by bog-dan-ro** [comment]
The search works ok.
Please check your internet connection.

**Comment by bobv46** [comment]
Awesome working now . Prob was my net or phone .awesome app thank u

Sent from my Samsung Galaxy smartphone.

-------- Original message --------
