### ISSUE TITLE
Online search uses Android keyboard

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#73]
I just tried the Online search for testing purposes and when you choose to type something the Android keyboard comes up. This means that people without touch screens will not be able to type.

**Comment by bog-dan-ro** [comment]
Android's keyboard on non-touch devices, can be used with the gamepad ;-)

**Comment by ghost** [comment]
It doesn't work on my device (GPD XD). Mine has built-in controls and a touch screen, maybe it only works on external gamepads without touch screen only. No worry.
