### ISSUE TITLE
Red warnings/tips messages stay on screen too long

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#74]
Is there any chance we can reduce the time the red messages display for ?

The red sound warning when first starting doesn't apply to my device because it sounds fine but the warning message stays on screen for about 10 seconds.

When mapping the pause function and using it the message is about 6 seconds.

**Comment by bog-dan-ro** [comment]
Touching on them will make them disappear immediately

**Comment by ghost** [comment]
Is there any chance you could change the 'paused' message to a pause symbol in one on the corners of the screen so nothing obstructs the image ?

**Comment by bog-dan-ro** [comment]
Not in 2.0 :)

**Comment by bog-dan-ro** [comment]
Also, the paused symbol will be visible all the time, and for sure it will cover someone else's important screen part, so, IMHO the message is ok for now, as long as you can hide it with a simple touch

**Comment by ghost** [comment]
You could make it slowly fade out like the Tape/Disk symbol and re-appear when you touch a button. It should be pretty obvious when it's paused. When you add the Fast Forward option in 3.0 you could use a fast forward symbol. Only suggestions.

**Comment by bog-dan-ro** [comment]
ok, please open an issue and I'll see what I can do :)
