### ISSUE TITLE
Font makes some menu items a bit too long and get cut off

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#75]
Visible on 'machine select' and 'customize gamepad buttons' menus.

**Comment by bog-dan-ro** [comment]
Thanks!

**Comment by bog-dan-ro** [comment]
Can you please add a screen with 'customize gamepad buttons' menus.

**Comment by ghost** [comment]
![screenshot_2016-06-17-16-29-53](https://cloud.githubusercontent.com/assets/12862298/16155819/07990260-34a9-11e6-9c21-837696b80d34.png)
![screenshot_2016-06-17-16-30-30](https://cloud.githubusercontent.com/assets/12862298/16155823/0ef2bfce-34a9-11e6-8f05-9247d2311e81.png)
This one is not too bad because you can see that the ... truncates the words.
![screenshot_2016-06-17-16-31-07](https://cloud.githubusercontent.com/assets/12862298/16155835/15ac0ab4-34a9-11e6-85db-ca33d0137e7f.png)
Maybe it only happens on small screens ?

**Comment by bog-dan-ro** [comment]
It happens only on **some** small screen devices, I'll try to force a larger width.

**Comment by ghost** [comment]
The gamepad button choice is OK because the words have '...' on the end to signify that it's truncated.

**Comment by bog-dan-ro** [comment]
Closed by https://github.com/bog-dan-ro/spectacol/commit/e83145e1ff7c269b45593fd94e3c2c3f1d20935d

**Comment by ghost** [comment]
Is the sidebar maybe a bit too wide now ? I think this is the longest name in the 'machine types' and now there's quite a bit of extra space at the end. Its up to you.
![screenshot_2016-06-17-23-38-50](https://cloud.githubusercontent.com/assets/12862298/16166695/67687798-34e5-11e6-99c3-a5d40509a82d.png)

Also, the configure gamepad buttons are still truncated until you choose something that has more letters than the previous option. For instance, if its on 'joystick fire' then some of the action choices are truncated, if you then choose 'toggle keyboard' it shows the full names. You may have done this on purpose.

**Comment by bog-dan-ro** [comment]
Actually "Spectrum 48K (NTSC)" is the longest. 
Because the font metrics are not the same on all devices I took an extra safe margin
