### ISSUE TITLE
Timex machines have different filtering, looks clearer

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#77]
When using 'Preserve Aspect Fit' the 'smooth scaling' option looks a lot clearer on Timex machines. Looks properly scaled.

**Comment by bog-dan-ro** [comment]
Is this a bug ?

**Comment by ghost** [comment]
I don't know but it looks better. If you turn on 'Preserve Aspect Fit' and 'Smooth Scaling' and switch machine types back and forth from Timex to something different. Maybe you can add this as an alternate 'less smooth' scaling.

**Comment by bog-dan-ro** [comment]
Timex screen is different from the common ZX Spectrum screens

**Comment by ghost** [comment]
So this can only look like this on Timex ?

**Comment by bog-dan-ro** [comment]
yep

**Comment by ghost** [comment]
Shouldn't the Pentagon etc. look clearer as well like the Timex because it says on Wikipedia that they have the same 8x1 attribute blocks, compared to the original spectrum's 8x8 ? I'm sure it's more complicated.
