### ISSUE TITLE
This happens when you press H on Pentagon

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#81]
![screenshot_2016-06-17-23-42-31](https://cloud.githubusercontent.com/assets/12862298/16166857/dd8afe4a-34e6-11e6-8c20-df36f5dedcf3.png)

What's that all about ? Is it built into the ROM ?

**Comment by bog-dan-ro** [comment]
If you mean the insulting message, than yes, it's built into the ROM ...
