### ISSUE TITLE
A couple of questions to ask

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#83]
1) How does the Kempston Mouse work ? I tried the game Carrier Command and selected Kempston Mouse but couldn't get the mouse pointer to move. I tried to move it with the touch screen and gamepad but no. Does it need a REAL mouse to use it ?

2) Are there any basic instructions on how to use the Poke Finder ? When it has found 1 possible location what do you do next ?

**Comment by bog-dan-ro** [comment]
1. It's not implemented yet
2. You need to set a breakpoint on write. Check https://youtu.be/V3wGcyB6ltU?t=207 for more info

**Comment by ghost** [comment]
On that video when you demonstrate the pokes with Manic Miner, you have a different keyboard and it looks like you're using the gamepad to type. I haven't got that and I have to use the touchscreen with the standard Android keyboard ? Why is this ? Do you only get that gamepad compatible keyboard if you don't have a touchscreen ? So if I HDMI my device to my TV I would still have to use the touchscreen ?

**Comment by bog-dan-ro** [comment]
I think it depends on the Android version... and probably also on the device manufacturer too. That device is a nvidia tv shield but AFAIK it uses a standard leanback keyboard from google. 
You can try to install  http://forum.xda-developers.com/nvidia-shield/themes-apps/share-android-tv-leanback-keyboard-t2815913 .

**Comment by ghost** [comment]
No it doesn't work on mine, i'll have to use the touchscreen only.
