### ISSUE TITLE
Joystick type changes to 'Cursor' when selecting RZX.

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#86]
'Snapshot joystick prompt' is OFF but keeps changing to 'Cursor' joystick when selecting RZX files.

**Comment by bog-dan-ro** [comment]
The RZX (or any snapshot) have the joystick information saved in the files, Spectacol (well fuse) just use that information to set it. When 'Snapshot joystick prompt' is on it just asks the user if the selected one is ok
