### ISSUE TITLE
Overlay buttons

### ISSUE THREAD

**Issue by maverick74** [bog-dan-ro/spectacol#88]
Y button overlays the Joystick On/Off button.

![bug](https://cloud.githubusercontent.com/assets/14912461/16203588/d780644e-3712-11e6-867b-6c64e046449b.jpg)

I think this could be solved by relocating the buttons or by using another approach (maybe a Slide for Keyboard OR Joystick, however this would still need an Show/Hide...)

Also... what about some new icons for Keyboard and Joystick buttons?! ;)

**Comment by bog-dan-ro** [comment]
Regarding the Keyboard and Joystick buttons I could not find any better (free) icons ;-)
