### ISSUE TITLE
Detects keypresses/joypad directions when paused

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#89]
To test, if you have a button set to pause and a button set for Space for example. If you press pause then press your button for space then unpause, the cursor will endlessly repeat space until you press another key. This also happens if you press a joystick direction while paused.

**Comment by bog-dan-ro** [comment]
I'm going to check it after I comeback from vacation (~10 from now)

**Comment by ghost** [comment]
OK, have a nice time and thanks for your hard work.
