### ISSUE TITLE
Tape Rewind & Tape Clear don't do anything

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#90]
A tape failed to load half way through (firebird loader) and had a lot of tape blocks so instead of scrolling back to near the beginning in the tape manager I tried 'Tape Rewind' but it didn't do anything.

I'm not sure what the 'Tape Clear' option is for or it's usefulness.

**Comment by bog-dan-ro** [comment]
Tape rewind doesn't seem to work.... regarding the 'Tape Clear' option I think is for clear the tape to write something else on top of it, but it doesn't seem to work either. I think I'm going to remove both if 'Tape Rewind' needs upstream changes
