### ISSUE TITLE
This happened when I loaded these two tapes ?

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#91]
In Spectrum 128k mode I loaded

[Castle Spellerous (1983) (Sinclair Research).tzx.zip](https://github.com/bog-dan-ro/spectacol/files/342297/Castle.Spellerous.1983.Sinclair.Research.tzx.zip)

It reset and the tape icon stayed on screen, I then loaded

[Castle, The (1983) (Bug-Byte Software).tzx.zip](https://github.com/bog-dan-ro/spectacol/files/342299/Castle.The.1983.Bug-Byte.Software.tzx.zip)

And this screen came up

![screenshot_2016-06-30-21-11-13](https://cloud.githubusercontent.com/assets/12862298/16502817/17ae3b0c-3f08-11e6-841d-4f3ef00ae934.png)

I then couldn't change Spectrum model or quit Spectacol properly.

**Comment by bog-dan-ro** [comment]
I'd like to get rid of all old widgets, but this task is time consuming and I don't want to delay 2.0 too much
