### ISSUE TITLE
Tapes don't load properly with 'detect loaders' off (no acceleration)

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#93]
If you turn off loader acceleration, tapes don't load properly if 'detect loaders' is turned off.

**Comment by bog-dan-ro** [comment]
Why do you want to turn off this option? I keep it as an option because there are rare cases where you need to turn it off to load some tapes.

**Comment by ghost** [comment]
When loader acceleration is OFF and detect loaders is ON it cuts out the blank gap between tape blocks and some loaders fail to load because of this (Chase HQ). But like I said in a previous post, the compatibility of Fuse is nowhere near Spectaculator and I don't understand why. I can't get Chase HQ (and some others) to load with any combination of Loading speeds yet it works in Android Spectaculator with the Fast Load option.

[Chase H.Q. (1989) (Ocean).zip](https://github.com/bog-dan-ro/spectacol/files/343300/Chase.H.Q.1989.Ocean.zip)

**Comment by bog-dan-ro** [comment]
I just try it with FUSE 1.2.0 (default settings) and it doesn't work either ...
There should be no difference between Spectacol and FUSE because, well Spectacol it's just an UI made with QML on top of FUSE.

**Comment by bog-dan-ro** [comment]
I test it again. You need to choose 48K machine and it works.

**Comment by ghost** [comment]
But the version I posted of Chase HQ is also 128k, it has different Music, Intro screen and loads all the levels. It doesn't work on Spectacol.

**Comment by bog-dan-ro** [comment]
It doesn't work on FUSE either if I choose 128K machine version ....

**Comment by ghost** [comment]
That's what I mean, poor compatibility (Fuse), it works in Spectaculator fast load. It works on Fuse if you turn OFF all acceleration and also turn OFF detect loaders but it takes about 5 minutes to load.

**Comment by bog-dan-ro** [comment]
Switching off loaders and choosing "None" Loader Acceleration also makes Spectacol to load it after waiting ages ....

**Comment by ghost** [comment]
But it doesn't start loading when opened from the Quick Open menu, you have to manually press play.

Yeah, I just checked and this happens on Fuse as well. Is there any reason why this can't be loaded with fastloaders and yet Spectaculator loads it no problem (and Spectaculators fast loader is much much quicker) ?

**Comment by bog-dan-ro** [comment]
I have no idea ... I think we'll need to upstream the bug. Will you do it? If yes, then please don't forget to link the bugs

**Comment by ghost** [comment]
A similar bug was already reported https://sourceforge.net/p/fuse-emulator/bugs/354/

**Comment by bog-dan-ro** [comment]
Depends on #103
