### ISSUE TITLE
Selecting Symbol Shift & Capshift makes cursor alternate rapidly

### ISSUE THREAD

**Issue by ghost** [bog-dan-ro/spectacol#99]
Can't enter the green keywords in 48k basic.

**Comment by bog-dan-ro** [comment]
You are talking about gamepad mode, right?
I don't think it can be made to alternate slowly ... Spectacol just press that key and keeps it pressed until you'll press it again. You just need to press it twice faster and that's it.

What I can do is to detect if SS is press when you press CS and release CS (or SS) immediately... But this is a task for 3.0 ;-)

**Comment by ghost** [comment]
Yes, gamepad mode. For example, some games need to be loaded with LOAD "" CODE, but to enter the CODE command you have to press Symbol Shift and Capshift to enter EXTEND mode, then press the 'I' key. Like you said, if the user presses Symbol Shift then Capshift (or vice versa) then deselect both and enter EXTEND mode, this is how it's done on the Spectaculator virtual keyboard.

Or you could add an optional alternate Spectrum + on-screen keyboard which has an EXTEND key.
